import Head from 'next/head'
import Image from 'next/image'
import HomeStyles from '../styles/Home.module.css'
import { GetStaticProps } from 'next'
import { getSortedPostsData } from '../lib/posts'
import Link from 'next/link'



const Home = ({allPostsData}:{
  allPostsData:{
    date:string
    title : string
    id : string
  }[]
}) => {
  return (
    <div className={HomeStyles.container}>
      <Head>
        <title>R1NM BLOG</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className={HomeStyles.headingMd}>
        <p>R1NM, A Cyber Security Engineer</p>
        <p>This is a simple website</p>
      </section>
      <section className={`${HomeStyles.headingMd} ${HomeStyles.padding1px}`}>
        <h2 className={HomeStyles.headingLg}>Blog</h2>
        <ul className={HomeStyles.list}>
          {/* posts */}
          {allPostsData.map(({id,title,date}) => 
            <li className={HomeStyles.listItem} key={id}>
              <Link href={`posts/${id}`}>
                {title}
              </Link>
              
              <br/>
              <small className={HomeStyles.lightText}>
                {date}
              </small>
            </li>
          )}
        </ul>
      </section>
      
    </div>
  )
}
export default Home;
export const getStaticProps: GetStaticProps = async () =>{
  const allPostsData = getSortedPostsData();
  return {
    props:{
      allPostsData
    }
  }

}